apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: weatherdata
spec:
  type: NodePort
  selector:
    app: api-service
  ports:
    - nodePort: 30080
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  namespace: weatherdata
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
      - name: api-service
        image: se23m015/api-service:main
        ports:
        - containerPort: 8080