apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-source-service
  namespace: weatherdata
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-source-service
  template:
    metadata:
      labels:
        app: data-source-service
    spec:
      containers:
      - name: data-source-service
        image: se23m015/data-source-service:main